version: 2.1
jobs:
    build:
        docker:
            - image: alpine:3.7
        steps:
            - checkout
            - run:
                name: The First Step
                command: |
                echo "Hello World!"
                echo "This is the Delivery Pipeline"
            - run:
                name: code has arrived
                command: |
                ls -la
                echo "^^^This should look Familiar^^^"
                   